name: Production Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          docker build -f Dockerfile.app . --tag stay:prod
          docker tag stay:prod smasher164/stay:prod
          docker login --username="smasher164" --password="${{ secrets.DOCKER_HUB_PASSWORD }}"
          docker push smasher164/stay:prod
      - uses: appleboy/ssh-action@master
        with:
          host: akhil.cc
          username: core
          key: ${{ secrets.PRIVATE_KEY }}
          script: docker pull smasher164/stay:prod && sudo systemctl restart stay